version: '3.8'
services:
    ping:
        build: 
            context: .  
            dockerfile: Dockerfile.local
        ports:
            - 5000:5000
        links:
            - pong
    pong:
        build:  
            context: .  
            dockerfile: Dockerfile.local
        ports:
            - 5001:5000
    redis:
        image: "redis:alpine"