version: '3.8'
services:
    ping:
        build: 
            context: .  
            dockerfile: Dockerfile
        ports:
            - 5000:5000
    pong:
        build:  
            context: .  
            dockerfile: Dockerfile
        ports:
            - 5001:5000
    #redis:
    #    image: "redis:alpine"